# Generated by Django 6.0.4 on 2026-04-24 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120)),
                ('image', models.ImageField(upload_to='portfolio/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Zdjęcie portfolio',
                'verbose_name_plural': 'Portfolio',
                'ordering': ['-created_at'],
            },
        ),
    ]
